feat: add depth flag
nix-community/nix-eval-jobs pull request #46
Opened 2022-03-23 00:54 UTC by tomberek

limit recursion to a default depth of 1

needs improvement: recursion is only the number of "."

Fixes: #10 #9

2022-03-23 07:05 UTC, Mic92 commented on src/nix-eval-jobs.cc
> +                    Bindings::iterator j = v->attrs->find(state.sRecurseForDerivations);
Can you make a test case for this or just extend this file? https://github.com/nix-community/nix-eval-jobs/blob/4bab9e449da80b58507d8d3ab6c051701e8d65e4/tests/assets/ci.nix#L6

2022-03-23 07:05 UTC, Mic92 commented on src/nix-eval-jobs.cc
> +                    Bindings::iterator j = v->attrs->find(state.sRecurseForDerivations);
Otherwise looks good to me.

2022-03-23 07:08 UTC, Mic92 commented on src/nix-eval-jobs.cc
> +            .longName = "depth",
I guess this is nice to preserve backwards compatibility but it should be also documented in the README.

2022-03-23 07:11 UTC, Mic92 commented
In general. Have you considered re-using: https://github.com/NixOS/nix/blob/d5d4d980427aca3849b90bfe1694b6d1d14532fb/src/libexpr/get-drvs.cc#L337
and if yes, what where the reasons not to copy the code?
The reason its not here used where because this was copied from hydra.

2022-03-23 11:25 UTC, tomberek commented
I copied the logic and code from “getDerivations”, but not using the function itself because I believed the intent is to keep using the parallel server/worker model on a per-attribute basis. “getDerivations” does a single threaded depth-first-search while this (and hydra) does a breadth-first parallel search.

2022-04-25 10:14 UTC, adisbladis commented
I really don't like to have a `depth` flag that defaults to some arbitrary low value since that wouldn't work well for evaluating trees.
I've gone ahead and implemented support for _only_ `recurseForDerivations` in #62. 

A depth flag should be completely separate and optional.

2022-04-25 10:20 UTC, adisbladis requested changes
This flag needs to be completely optional and not default to some arbitrary low value that would break tree evaluation.

2022-04-25 14:01 UTC, adisbladis requested changes

2022-04-25 14:01 UTC, adisbladis commented on src/nix-eval-jobs.cc
> +    size_t depth = 1;
I suggest having the flag default to 0 meaning no limit.

2022-04-25 14:01 UTC, adisbladis commented on src/nix-eval-jobs.cc
> +                size_t n = std::count(attrPath.begin(), attrPath.end(), '.')+(attrPath == "" ? 0: 1);
This is fine for now and would be addressed by #43.

2022-04-25 14:01 UTC, adisbladis commented on src/nix-eval-jobs.cc
> +                size_t n = std::count(attrPath.begin(), attrPath.end(), '.')+(attrPath == "" ? 0: 1);
This is fine for now and would be addressed by #43.

2022-04-25 14:01 UTC, adisbladis commented on src/nix-eval-jobs.cc
> +                    Bindings::iterator j = v->attrs->find(state.sRecurseForDerivations);
`recurseForDerivation` support was added in #62 so it's not required here any more.

2022-04-25 14:01 UTC, adisbladis commented on src/nix-eval-jobs.cc
> +                    Bindings::iterator j = v->attrs->find(state.sRecurseForDerivations);
`recurseForDerivation` support was added in #62 so it's not required here any more.

2023-01-22 10:21 UTC, Mic92 commented
This PR has been stalled. Please re-open if you plan to continue working on this.

2023-01-22 10:21 UTC, closed without merging